api_platform:
    title: Task API Platform
    description: 'API description'
    version: 1.0.0
    openapi:
        contact:
            name: 'Kuanysh'
            email: 'kuanish@mail.kz'
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
